language: C
matrix:
  include:
    - os: linux
      sudo: false
      compiler: clang
    - os: linux
      sudo: false
      compiler: gcc
    - os: osx
      compiler: clang
script: make && make test
