language: C
jobs:
  include:
    - stage: C style check
      script: ./dev/style.sh
    - stage: test
      os: linux
      name: Xenial + Clang
      dist: xenial
      sudo: false
      compiler: clang
      script: ./dev/test.sh
    - stage: test
      os: linux
      name: Xenial + GCC
      dist: xenial
      sudo: false
      compiler: gcc
      script: ./dev/test.sh
    - stage: test
      os: linux
      name: Bionic + GCC 7
      dist: bionic
      sudo: false
      compiler: gcc
      script: ./dev/test.sh
    - stage: test
      os: osx
      name: macOS + Clang
      compiler: clang
      script: ./dev/test.sh
