language: C
matrix:
  include:
    - os: linux
      name: Xenial + Clang
      dist: xenial
      sudo: false
      compiler: clang
    - os: linux
      name: Xenial + GCC
      dist: xenial
      sudo: false
      compiler: gcc
    - os: linux
      name: Bionic + GCC 7
      dist: bionic
      sudo: false
      compiler: gcc
    - os: osx
      name: macOS + Clang
      compiler: clang
# Travis default script uses ./configure which is not present here.
script: make && make test
